### PR TITLE
Fix compatibility with curl 7.87.0

### LINKED ISSUE #70: test: failures with libcurl 7.87.0
> 1:       expected: response reading failed
> 1:       got: 'response reading failed (errno: 115)'

> 1:       expected: -1
> 1:       got: 250

Observed in https://github.com/tarantool/tarantool/pull/8151#issuecomment-1382190651.

### PR DESCRIPTION
**Pull request by ligurio**
Fixes #70 
Required for https://github.com/tarantool/tarantool/pull/8151

### CODE REVIEW

File: smtp/lib.c [hunk 1]
```diff
@@ -265,6 +275,7 @@ luaT_smtpc_cleanup(lua_State *L)
 
 static const struct luaL_Reg Module[] = {
 	{"new", luaT_smtpc_new},
+	{"__CURL_VERSION", luaT_smtpc_version},
```
Comment (Totktonada) [inline smtp/lib.c]: Can we call it in `luaopen_smtp_lib()` and fill the field using `lua_setfield()`?

The uppercased function name looks quite unusual.

Or lowercase it.

File: smtp/smtpc.h [hunk 2]
```diff
@@ -267,4 +267,16 @@ smtpc_execute(struct smtpc_request *req, double timeout);
...
 
+/* {{{ Version */
+
+/**
+ * Get a Curl library version.
+ *
+ * @see https://curl.se/libcurl/c/curl_version_info.html
+ */
+void
+get_curl_version(char *version, size_t len);
```
Comment (Totktonada) [inline smtp/smtpc.h]: The function doesn't follow the `smtpc_*` name pattern.

File: smtp/lib.c (hunk 1 above)
Comment (Totktonada) [reply smtp/lib.c]: I see, it is called in `init.lua` and stored as a field. Okay. So, up to you.

File: test/smtp.test.lua [hunk 3]
```diff
@@ -1,13 +1,33 @@
...
+    return tonumber(major), tonumber(minor), tonumber(patch)
+end
+
+-- Whether current curl version is greater or equal to the provided one.
+local function is_curl_version_ge(maj, min, patch)
+    local cur_maj, cur_min, cur_patch = curl_version()
+    return (cur_maj >= maj) and
+           (cur_min >= min) and
+           (cur_patch >= patch)
+end
```
Comment (Totktonada) [inline test/smtp.test.lua]: Is 3.2.1 >= 1.2.3? This function gives `false`.

There are some implementatoin of version comparison code you may be interested in: https://github.com/tarantool/tarantool/discussions/7006.

File: test/smtp.test.lua [hunk 4]
```diff
@@ -1,13 +1,33 @@
...
+
+print(string.format('# libcurl version: %s', smtp.__CURL_VERSION))
```
Comment (Totktonada) [inline test/smtp.test.lua]: BTW, there is `test:diag()`.

File: smtp/smtpc.c [hunk 5]
```diff
@@ -466,7 +466,8 @@ smtpc_execute(struct smtpc_request *req, double timeout)
 		 * response code stays 250, that is not correct. See
 		 * https://github.com/curl/curl/issues/8356
 		 */
-		if (strcmp(req->error_buf, "response reading failed") == 0) {
+		const char msg[] = "response reading failed";
+		if (strncmp(req->error_buf, msg, sizeof(msg)) == 0) {
 			req->status = -1;
 		}
```
Comment (Totktonada) [inline smtp/smtpc.c]: I would leave a comment that we comparing by starting bytes here.

BTW, we should do `sizeof() - 1` for that.

File: test/smtp.test.lua (hunk 4 above)
Comment (ligurio) [reply test/smtp.test.lua]: Fixed:

```diff
--- a/test/smtp.test.lua
+++ b/test/smtp.test.lua
@@ -26,8 +26,7 @@ local function is_curl_version_ge(maj, min, patch)
            (cur_patch >= patch)
 end
 
-print(string.format('# libcurl version: %s', smtp.__CURL_VERSION))
-
+test:diag(string.format('libcurl version: %s', smtp.__CURL_VERSION))
 test:plan(1)
 local mails = fiber.channel(100)
 
```

```
1: TAP version 13              
1: # libcurl version: 7.84.0-DEV
1: 1..1  
...
```

File: smtp/smtpc.c (hunk 5 above)
Comment (ligurio) [reply smtp/smtpc.c]: Added a comment, renamed variable to `msg_prefix` and fixed size:

```diff
--- a/smtp/smtpc.c
+++ b/smtp/smtpc.c
@@ -465,9 +465,12 @@ smtpc_execute(struct smtpc_request *req, double timeout)
                 * leads to a message about failed response reading but
                 * response code stays 250, that is not correct. See
                 * https://github.com/curl/curl/issues/8356
+                *
+                * NOTE: An error message could contain an errno,
+                * so we comparing start bytes only.
                 */
-               const char msg[] = "response reading failed";
-               if (strncmp(req->error_buf, msg, sizeof(msg)) == 0) {
+               const char msg_prefix[] = "response reading failed";
+               if (strncmp(req->error_buf, msg_prefix, sizeof(msg_prefix) - 1) == 0) {
                        req->status = -1;
                }
                req->reason = req->error_buf;
```

File: smtp/smtpc.h (hunk 2 above)
Comment (ligurio) [reply smtp/smtpc.h]: This function actually has nothing in common with smtp module.
Okay, let's add a prefix `smtp_`.

Comment (Totktonada) [reply smtp/smtpc.h]: `smtp*c*_`

It is in the smptc compilation unit. If it shouldn't be there, it is better to move it outside.

However we call libcurl function via this compilation unit, so it seems logical to have it there and have the `smtpc_` prefix.

Comment (ligurio) [reply smtp/smtpc.h]: already fixed

File: test/smtp.test.lua (hunk 3 above)
Comment (ligurio) [reply test/smtp.test.lua]: Heh, thanks for pointing to this, updated.

```diff
--- a/test/smtp.test.lua
+++ b/test/smtp.test.lua
@@ -21,9 +21,17 @@ end
 -- Whether current curl version is greater or equal to the provided one.
 local function is_curl_version_ge(maj, min, patch)
     local cur_maj, cur_min, cur_patch = curl_version()
-    return (cur_maj >= maj) and
-           (cur_min >= min) and
-           (cur_patch >= patch)
+
+    if cur_maj < maj then return false end
+    if cur_maj > maj then return true end
+
+    if cur_min < min then return false end
+    if cur_min > min then return true end
+
+    if cur_patch < patch then return false end
+    if cur_patch > patch then return true end
+
+    return true
 end
 
 test:diag(string.format('libcurl version: %s', smtp.__CURL_VERSION))
```

File: smtp/lib.c (hunk 1 above)
Comment (ligurio) [reply smtp/lib.c]: Updated, curl's version is in `require("smtp")._CURL_VERSION` as discussed.

File: test/smtp.test.lua (hunk 4 above)
Comment (ligurio) [reply test/smtp.test.lua]: Fixed curl version, now it is missed "-DEV" postfix.
```
Checking test dependency graph end
test 1                   
    Start 1: smtp              
                                   
1: Test command: /home/sergeyb/sources/MRG/smtp/test/smtp.test.lua
1: Working Directory: /home/sergeyb/sources/MRG/smtp/build
1: Environment variables:                                             
1:  LUA_PATH=/home/sergeyb/sources/MRG/smtp/?.lua;/home/sergeyb/sources/MRG/smtp/?/init.lua;
1: Test timeout computed to be: 10000000
1: started               
1: TAP version 13              
1: # libcurl version: 7.84.0
1: 1..1   
...
```

File: test/smtp.test.lua [hunk 6]
```diff
@@ -292,7 +292,11 @@ test:test("smtp.client", function(test)
     r = client:request(addr, 'sender@tarantool.org',
                        'breakconnect@tarantool.org',
                        'mail.body')
-    test:is(r.reason, 'response reading failed', 'unexpected response code')
+    local expected_reason = 'response reading failed'
+    if is_curl_version_ge(7, 86, 0) == true then
+        expected_reason = 'response reading failed (errno: 115)'
+    end
+    test:is(r.reason, expected_reason, 'unexpected response code')
     test:is(r.status, -1, 'expected code')
```
Comment (Totktonada) [inline test/smtp.test.lua:304]: There is the similar text case above (but it breaks a connection at processing a sender field). It should be updated too, otherwise the test fails on curl 7.87.0 (tested locally).

```diff
diff --git a/test/smtp.test.lua b/test/smtp.test.lua
index 5805647..86c1227 100755
--- a/test/smtp.test.lua
+++ b/test/smtp.test.lua
@@ -268,7 +268,11 @@ test:test("smtp.client", function(test)
     r = client:request(addr, 'breakconnect@tarantool.org',
                        'receiver@tarantool.org',
                        'mail.body')
-    test:is(r.reason, 'response reading failed', 'unexpected response code')
+    local expected_reason = 'response reading failed'
+    if is_curl_version_ge(7, 86, 0) == true then
+        expected_reason = 'response reading failed (errno: 115)'
+    end
+    test:is(r.reason, expected_reason, 'unexpected response code')
     test:is(r.status, -1, 'expected code')
 
     r = client:request(addr, 'sender@tarantool.org',
```

**Review by Totktonada — APPROVED** [review]
Thank you for the patches!

Aside of one forgotten check the patchset looks okay. I'm ready to apply it after the fix.

File: test/smtp.test.lua (hunk 6 above)
Comment (ligurio) [reply test/smtp.test.lua:304]: Updated:

```diff
--- a/test/smtp.test.lua
+++ b/test/smtp.test.lua
@@ -268,7 +268,11 @@ test:test("smtp.client", function(test)
     r = client:request(addr, 'breakconnect@tarantool.org',
                        'receiver@tarantool.org',
                        'mail.body')
-    test:is(r.reason, 'response reading failed', 'unexpected response code')
+    local expected_reason = 'response reading failed'
+    if is_curl_version_ge(7, 86, 0) == true then
+        expected_reason = 'response reading failed (errno: 115)'
+    end
+    test:is(r.reason, expected_reason, 'unexpected response code')
     test:is(r.status, -1, 'expected code')
 
     r = client:request(addr, 'sender@tarantool.org',
```

**Review by Totktonada — APPROVED** [review]
