### PR TITLE
curl: unable to load libcurl.so

### LINKED ISSUE #44: Unable to load libcurl.so
## Affected versions

Affected versions of the module: 0.0.5+ (where we added the falling back to the system libcurl). Previous versions of the module may fail on those tarantool versions due to other reasons and with other disagnostics (see #24 and #29).

The problem appears on all tarantool versions, where the module falls back to system libcurl: all versions prior to 1.10.10, 2.6.3, 2.7.2, 2.8.1.

## How it looks

When run a script with `require('smtp')`:

```
Unable to load symbol curl_easy_cleanup from [tarantool]
Attempt to fallback to libcurl.so
ER_SYSTEM: Unable to load libcurl.so
fatal error, exiting the event loop
```

In the interactive console:

```yaml
tarantool> require('smtp')
Unable to load symbol curl_easy_cleanup from [tarantool]
Attempt to fallback to libcurl.so
---
- error: Unable to load libcurl.so
...
```

## When it appears and when not

The problem appears when the module falls back to the system libcurl (on relatively old tarantool versions) and when there is no dynamic library named exactly as 'libcurl.so' (without the version suffix). This situation usually occurs, when the module is installed from an RPM or Deb package and the developer libcurl package is not installed.

## Workarounds

While the problem is not fixed in the module, the following recipes should help to mitigate it.

### Install libcurl developer package (recommended)

The developer libcurl package provides libcurl.so -> libcurl.so.4.X.Y symlink.

On Debian or Ubuntu (verified on Debian Buster):

```sh
$ apt-get install libcurl4-openssl-dev
```

On CentOS or Fedora (verified on CentOS 7):

```sh
$ yum install libcurl-devel
```

### Create the symlink manually (alternative)

This option is not recommended.

On Debian or Ubuntu:

```sh
$ cd /usr/lib/x86_64-linux-gnu
$ ln -s libcurl.so.4 libcurl.so
$ ldconfig
```

On CentOS or Fedora:

```sh
$ cd /usr/lib64
$ ln -s libcurl.so.4 libcurl.so
$ ldconfig
```

### PR DESCRIPTION
**Pull request by vr009**
The problem appears when the module falls back to the system libcurl
(on relatively old tarantool versions) and when there is no dynamic library
named exactly as 'libcurl.so' (without the version suffix). This situation
usually occurs, when the module is installed from an RPM or Deb package
and the developer libcurl package is not installed.

Fixes #44

### CODE REVIEW

**Review by ligurio — CHANGES_REQUESTED** [review]
Thanks for the patch!

Why all builds for macOS has failed?

```
-- Using bundled ZSTD
-- Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the system variable OPENSSL_ROOT_DIR (missing: OPENSSL_INCLUDE_DIR) 
CMake Error at CMakeLists.txt:328 (message):
  Could NOT find OpenSSL development files (libssl-dev/openssl-devel package)
```

**Comment by vr009** [comment]
> Why all builds for macOS has failed?
> 
> ```
> -- Using bundled ZSTD
> -- Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the system variable OPENSSL_ROOT_DIR (missing: OPENSSL_INCLUDE_DIR) 
> CMake Error at CMakeLists.txt:328 (message):
>   Could NOT find OpenSSL development files (libssl-dev/openssl-devel package)
> ```

That problem relates to #49. I am currently fixing it.

**Comment by ligurio** [comment]
> That problem relates to #49. I am currently fixing it.

Well, then we wait for a fix of #49.

The proposed change adds a condition specific for FreeBSD. It means that we need to build and test on FreeBSD in CI too.

**Comment by Totktonada** [comment]
> The proposed change adds a condition specific for FreeBSD. It means that we need to build and test on FreeBSD in CI too.

Wow. I'm okay with just results on manual testing on FreeBSD shared here.

When we'll have an infrastructure for clean (created for a job) autoscaled self-hosted runners I'll be okay to add them into modules.

**Comment by ligurio** [comment]
> When we'll have an infrastructure for clean (created for a job) autoscaled self-hosted runners I'll be okay to add them into modules.

It looks as a typical perfectionism: wait when our ideal CI infrastructure will work fine. Instead of using FreeBSD on cloud CI that just works (yep, I mean Cirrus CI).

Get me right: code that doesn't work is a dead code. FreeBSD-specific code is a dead code now.

**Comment by Totktonada** [comment]
I like the idea with Cirrus CI. However for this particular change it will be okay for me if Slava will just share testing results on FreeBSD.

File: smtp/smtpc.c [hunk 1]
```diff
@@ -158,9 +158,9 @@ smtpc_init(void)
 
 	const char *libname;
 #ifdef __APPLE__
-	libname = "libcurl.dylib";
+	libname = "libcurl.4.dylib";
```
Comment (Totktonada) [inline smtp/smtpc.c:161]: Regarding Mac OS: the system library is versioned (has `.4`) and the library from homebrew as well, correct?

**Comment by Totktonada** [comment]
Don't forget to enable the releavent testing job:

https://github.com/tarantool/smtp/blob/e17aad31f8caf1143374abaa0216d1651272afac/.github/workflows/packaging.yml#L77-L81

**Comment by Totktonada** [comment]
The idea of the fix looks is okay, but I would highlight an alternative just in case.

Now we do the following:

* Try tarantool's built-in libcurl.
* Try `libcurl.so` / `libcurl.dylib`.
* Fail if no attempts were successful.

The safe way to fix the problem would be change the algorithm to the following:

* Try tarantool's built-in libcurl.
* Try `libcurl.so.4` / `libcurl.4.dylib`.
* Try `libcurl.so` / `libcurl.dylib`.
* Fail if no attempts were successful.

Is it possible that we'll have non-versioned library and will have no versioned one? I doubt about this. Disregard so. However we can return here if we'll see an actual problem.

File: smtp/smtpc.c (hunk 1 above)
Comment (vr009) [reply smtp/smtpc.c:161]: Yes, that's right.

**Comment by vr009** [comment]
> Don't forget to enable the releavent testing job:
> 
> https://github.com/tarantool/smtp/blob/e17aad31f8caf1143374abaa0216d1651272afac/.github/workflows/packaging.yml#L77-L81

Sure I will enable this jobs, but I have faced a problem which is described in related patch #52. After this one will be solved I will check all other jobs for passing.

**Comment by vr009** [comment]
> Is it possible that we'll have non-versioned library and will have no versioned one? I doubt about this. Disregard so. However we can return here if we'll see an actual problem.

Okay, I'm not sure that it is possible to have a non-versioned library without the versioned one.

File: smtp/smtpc.c (hunk 1 above)
Comment (Totktonada) [reply smtp/smtpc.c:161]: Okay so.

**Comment by Totktonada** [comment]
Let's rebase after PR #52 and don't forget to uncomment related CI rules (see above).

**Comment by vr009** [comment]
I have tried this changes on FreeBSD 12.2 and I had just one case when this module tries to fall back to system curl. That occurs with tarantool releases 1.10.x. The output was always like:
`root@freebsd:~/smtp # /root/tarantool/build/src/tarantool`
`Tarantool 1.10.7-0-g554d439a5`
`type 'help' for interactive help`
`tarantool> smtp = require('smtp').new()`
`Unable to load symbol curl_easy_cleanup from [tarantool]`
`Attempt to fallback to libcurl.so.4`
`Successfully loaded libcurl.so.4`

This fall back is also succesful with non-versioned libcurl, so we have both working options.

File: .github/workflows/packaging.yml [hunk 2]
```diff
@@ -73,13 +73,13 @@ jobs:
...
-          # distribution versions, which are not supported by
-          # tarantool 1.10.7.
-          # - release/1.10.7
+          - release/1.10.7
           - live/2.9
+        exclude:
+          - platform: {os: debian, dist: bullseye}
+            tarantool: release/1.10.7
+          - platform: {os: fedora, dist: 34}
+            tarantool: release/1.10.7
```
Comment (Totktonada) [inline .github/workflows/packaging.yml]: Please, leave a comment with the reason of excluding. It may be not so obvious.

**Review by Totktonada — APPROVED** [review]
LGTM.

File: .github/workflows/packaging.yml (hunk 2 above)
Comment (vr009) [reply .github/workflows/packaging.yml]: Added.

**Review by ligurio — APPROVED** [review]
LGTM
